name: Debian Buster Image

on:
  push:
    branches: [ buster ]
  pull_request:
    branches: [ buster ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dftechs_debian_buster:$(date +%s)
