name: Debian bullseye Image

on:
  push:
    branches: [ bullseye ]
  pull_request:
    branches: [ bullseye ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dftechs_debian_bullseye:$(date +%s)
